name: atriel
channels:
- conda-forge
- nodefaults
dependencies:
- pip=24.0
- python=3.12.2
- pip:
  - hydra-core=1.3.2
  - imutils=0.5.4
  - matplotlib=3.8.3
  - numpy=1.26.4
  - omegaconf=2.3.0
  - opencv-python=4.9.0.80
  - pre-commit=3.6.2
  - scikit-image=0.22.0
  - tqdm=4.66.2
