name: atriel
channels:
- conda-forge
- nodefaults
dependencies:
- pip=24.0
- python=3.12.2
- pip:
  - gradio==4.21.0
  - hydra-core==1.3.2
  - imutils==0.5.4
  - joblib==1.3.2
  - matplotlib==3.8.3
  - numpy==1.26.4
  - omegaconf==2.3.0
  - opencv-python==4.9.0.80
  - paramiko==3.4.0
  - pre-commit==3.6.2
  - python-dotenv==1.0.1
  - scikit-image==0.22.0
  - tqdm==4.66.2
