defaults:
- main
- _self_

data_dir: data/csv_generation/
save_dir: data/csv_generation/
pins_per_day:
  canva-instagram-templates: 7
  instagram-highlight-covers: 2
  instagram-puzzle-feed: 1
  business-cards: 0
  airbnb-welcome-book: 0
  price-and-service-guide: 0
num_days: 2
copy_files_to_server: false
remove_local_files: false
start_date: 2024-05-25 # Format: YYYY-MM-DD for example 2024-05-25
seed: 11
