defaults:
- main
- _self_

data_dir: data/csv_generation/
save_dir: data/csv_generation/
pins_per_day:
  canva-instagram-templates: 3
  instagram-highlight-covers: 2
  instagram-puzzle-feed: 1
  business-cards: 0
num_csv_files: 2
max_pins_per_csv: 50
start_date: # if None, use current date
