defaults:
- main
- _self_

data_dir: data/input/highlights
save_dir: data/output/highlights
num_images: 10
scaling_factor: 1
include_samples: []   # Example: "01"
exclude_samples: []   # Example: "01"
seed: 11
